{
 "title": "Observabilidad - Proyecto Integrador",
 "tags": [
  "devops",
  "observabilidad",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Solicitudes HTTP por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(app_http_requests_total[1m]))",
     "legendFormat": "solicitudes"
    }
   ]
  },
  {
   "title": "Solicitudes por codigo HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(app_http_requests_total[1m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Tiempo de respuesta P95",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Memoria utilizada por Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "app_process_resident_memory_bytes",
     "legendFormat": "RSS"
    },
    {
     "expr": "app_nodejs_heap_size_used_bytes",
     "legendFormat": "Heap usado"
    }
   ]
  },
  {
   "title": "CPU del Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(app_process_cpu_seconds_total[5m])",
     "legendFormat": "CPU proceso"
    }
   ]
  }
 ]
}